import Counter from "@/components/Counter";
import Descriptions from "@/components/Descriptions";
import Dog from "@/components/Dog";
import Parent from "@/components/Parent";
import User from "@/components/User";
import Welcome from "@/components/Welcome";
import Head from "next/head";

export default function Home() {
  return (
    <>
      {/*Fragment*/}
      <Head>
        <title>Fundamentos do React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello World!</h1>
        {/* Chamando o componente */}
        <Welcome />
        {/* Importando o componente user que possui uma expressão JSX */}
        <User />
        {/* Componente pai que possui um componente filho incorporado */}
        <Parent />
        {/* Chamando o componente e passando as props para o mesmo:  */}
        <Descriptions name="Ana" age={18} />
        {/* Usando a desestruturação para passar props */}
        <Dog name="Rex" breed="PitBull" />
        <Counter/>
      </main>
    </>
  );
}
